# Generated by Django 5.1.7 on 2025-04-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('performance', models.FloatField()),
                ('stocks_count', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=50)),
                ('current_price', models.FloatField()),
                ('high_52w', models.FloatField()),
                ('low_52w', models.FloatField()),
                ('pe_ratio', models.FloatField(null=True)),
                ('market_cap', models.FloatField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['sector'], name='stocks_stoc_sector_6c2055_idx'), models.Index(fields=['high_52w'], name='stocks_stoc_high_52_d34745_idx')],
            },
        ),
    ]
