# Generated by Django 5.2 on 2025-04-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topsector',
            name='performance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Overall sector performance metric', max_digits=10),
        ),
        migrations.AddField(
            model_name='topsector',
            name='stocks_count',
            field=models.IntegerField(default=0, help_text='Number of stocks in this sector'),
        ),
    ]
