# Generated by Django 5.1.7 on 2025-04-02 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_stock_pe_ratio'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stock',
            new_name='stocks_stoc_sector__b8cedc_idx',
            old_name='stocks_stoc_sector_6c2055_idx',
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stocks.topsector'),
        ),
    ]
