# Generated by Django 5.1.7 on 2025-04-02 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_rename_stocks_stoc_sector__b8cedc_idx_stocks_stoc_sector_6c2055_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sector_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_stocks', to='stocks.topsector'),
        ),
    ]
