# Generated by Django 5.1.7 on 2025-04-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_rename_stocks_stoc_sector_6c2055_idx_stocks_stoc_sector__b8cedc_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stock',
            new_name='stocks_stoc_sector_6c2055_idx',
            old_name='stocks_stoc_sector__b8cedc_idx',
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(max_length=100),
        ),
    ]
